import test from "node:test";
import assert from "node:assert/strict";
import { getRuntimeCppSource, getRuntimeHeaderSource } from "../src/cpp/runtime-source.js";

test("runtime system-module helpers stay explicit and bounded", () => {
  const header = getRuntimeHeaderSource();
  const runtime = getRuntimeCppSource();

  assert.match(header, /value fs_remove_path\(const std::string& pathText\);/);
  assert.match(header, /value fs_remove_path_async\(const std::string& pathText\);/);
  assert.match(header, /value fs_list_directory\(const std::string& pathText\);/);
  assert.match(header, /value fs_list_directory_async\(const std::string& pathText\);/);
  assert.match(header, /value fs_rename_path\(const std::string& fromPathText, const std::string& toPathText\);/);
  assert.match(header, /value fs_rename_path_async\(const std::string& fromPathText, const std::string& toPathText\);/);
  assert.match(header, /value fs_stat_path\(const std::string& pathText\);/);
  assert.match(header, /value fs_stat_path_async\(const std::string& pathText\);/);
  assert.match(header, /value stream_open_read_async\(const std::string& pathText\);/);
  assert.match(header, /value stream_read_chunk_async\(const value& stream, int size\);/);
  assert.match(header, /value stream_close_async\(const value& stream\);/);
  assert.match(runtime, /value fs_async_result\(std::function<value\(\)> operation\) \{\s*const auto result = make_pending_async\(\);/);
  assert.match(runtime, /async_schedule\(\[result, operation = std::move\(operation\)\]\(\) mutable \{/);
  assert.match(runtime, /async_resolve\(result, operation\(\)\);/);
  assert.match(header, /struct stream_state/);
  assert.match(runtime, /value stream_open_read_async\(const std::string& pathText\)/);
  assert.match(runtime, /value stream_write_chunk_async\(const value& input, const value& bytesValue\)/);
  assert.match(runtime, /Jayess stream handle is already closed/);
  assert.match(header, /value path_resolve_parts\(const std::vector<std::string>& parts\);/);
  assert.match(header, /value path_relative_between\(const std::string& fromPathText, const std::string& toPathText\);/);
  assert.match(header, /value path_is_absolute\(const std::string& pathText\);/);
  assert.match(header, /void process_set_argv\(std::vector<std::string> args\);/);
  assert.match(header, /value process_get_argv\(\);/);
  assert.match(header, /value process_has_env\(const std::string& key\);/);
  assert.match(header, /value process_set_exit_code\(int code\);/);
  assert.match(header, /value os_platform\(\);/);
  assert.match(header, /value os_arch\(\);/);
  assert.match(header, /value os_home_directory\(\);/);
  assert.match(header, /value os_temporary_directory\(\);/);
  assert.match(header, /value os_hostname\(\);/);
  assert.match(header, /value os_newline\(\);/);
  assert.match(runtime, /std::vector<std::string> process_argv_storage;/);
  assert.match(runtime, /int process_exit_code_storage = 0;/);
  assert.match(runtime, /value fs_remove_path\(const std::string& pathText\) \{/);
  assert.match(runtime, /return std::filesystem::remove\(fs_require_path\(pathText\)\);/);
  assert.match(runtime, /value fs_remove_path_async\(const std::string& pathText\) \{/);
  assert.match(runtime, /return fs_async_result\(\[pathText\]\(\) \{ return fs_remove_path\(pathText\); \}\);/);
  assert.match(runtime, /value fs_list_directory\(const std::string& pathText\) \{/);
  assert.match(runtime, /for \(const auto& entry : std::filesystem::directory_iterator\(fs_require_path\(pathText\)\)\) \{/);
  assert.match(runtime, /std::sort\(entryNames\.begin\(\), entryNames\.end\(\)\);/);
  assert.match(runtime, /return make_array\(fs_string_values\(entryNames\)\);/);
  assert.match(runtime, /value fs_rename_path\(const std::string& fromPathText, const std::string& toPathText\) \{/);
  assert.match(runtime, /std::filesystem::rename\(/);
  assert.match(runtime, /return value\(std::monostate\{\}\);/);
  assert.match(runtime, /value fs_stat_path\(const std::string& pathText\) \{/);
  assert.match(runtime, /const auto exists = std::filesystem::exists\(pathValue, error\);/);
  assert.match(runtime, /const auto isFile = exists && std::filesystem::is_regular_file\(pathValue, error\);/);
  assert.match(runtime, /const auto isDirectory = exists && std::filesystem::is_directory\(pathValue, error\);/);
  assert.match(runtime, /return make_object\(\{/);
  assert.match(runtime, /\{"exists", exists\}/);
  assert.match(runtime, /\{"size", sizeValue\}/);
  assert.match(runtime, /value path_resolve_parts\(const std::vector<std::string>& parts\) \{/);
  assert.match(runtime, /resolved = std::filesystem::current_path\(\) \/ part;/);
  assert.match(runtime, /return path_string_value\(resolved\.lexically_normal\(\)\);/);
  assert.match(runtime, /value path_relative_between\(const std::string& fromPathText, const std::string& toPathText\) \{/);
  assert.match(runtime, /std::filesystem::relative\(/);
  assert.match(runtime, /value path_is_absolute\(const std::string& pathText\) \{/);
  assert.match(runtime, /return path_require_filesystem_path\(pathText\)\.is_absolute\(\);/);
  assert.match(runtime, /void process_set_argv\(std::vector<std::string> args\) \{/);
  assert.match(runtime, /process_argv_storage = std::move\(args\);/);
  assert.match(runtime, /value process_get_argv\(\) \{/);
  assert.match(runtime, /return make_array\(process_string_values\(process_argv_storage\)\);/);
  assert.match(runtime, /value process_has_env\(const std::string& key\) \{/);
  assert.match(runtime, /value process_set_exit_code\(int code\) \{/);
  assert.match(runtime, /value os_platform\(\) \{/);
  assert.match(runtime, /return std::string\("linux"\);/);
  assert.match(runtime, /value os_arch\(\) \{/);
  assert.match(runtime, /return std::string\("arm64"\);/);
  assert.match(runtime, /value os_home_directory\(\) \{/);
  assert.match(runtime, /return os_environment_string\("HOME"\);/);
  assert.match(runtime, /value os_temporary_directory\(\) \{/);
  assert.match(runtime, /std::filesystem::temp_directory_path\(\)/);
  assert.match(runtime, /value os_hostname\(\) \{/);
  assert.match(runtime, /os_environment_string\("HOSTNAME"\)/);
  assert.match(runtime, /value os_newline\(\) \{/);
});

test("runtime thread helpers stay explicit and transfer values across workers", () => {
  const header = getRuntimeHeaderSource();
  const runtime = getRuntimeCppSource();

  assert.match(header, /struct thread_state;/);
  assert.match(header, /using thread_ptr = std::shared_ptr<thread_state>;/);
  assert.match(header, /value thread_spawn\(const value& callback, const value& args\);/);
  assert.match(header, /value thread_join\(const value& input\);/);
  assert.match(header, /value thread_sleep_for_milliseconds\(int milliseconds\);/);
  assert.match(header, /value thread_hardware_concurrency\(\);/);
  assert.match(header, /value thread_current_id\(\);/);
  assert.match(runtime, /struct thread_state \{/);
  assert.match(runtime, /std::thread worker;/);
  assert.match(runtime, /std::mutex mutex;/);
  assert.match(runtime, /bool detached = false;/);
  assert.match(runtime, /value transfer_thread_value\(const value& input\)/);
  assert.match(runtime, /Value cannot cross a Jayess thread boundary/);
  assert.match(runtime, /value thread_spawn\(const value& callback, const value& args\)/);
  assert.match(runtime, /callable->fn\(transferredArgs\)/);
  assert.match(runtime, /value thread_join\(const value& input\)/);
  assert.match(runtime, /Jayess thread handle has already been joined/);
  assert.match(runtime, /value thread_sleep_for_milliseconds\(int milliseconds\)/);
  assert.match(runtime, /value thread_hardware_concurrency\(\)/);
  assert.match(runtime, /value thread_current_id\(\)/);
});

test("runtime time helpers stay monotonic and millisecond-based", () => {
  const header = getRuntimeHeaderSource();
  const runtime = getRuntimeCppSource();

  assert.match(header, /value time_millis\(\);/);
  assert.match(header, /value time_seconds\(const value& input\);/);
  assert.match(header, /value time_minutes\(const value& input\);/);
  assert.match(header, /value time_elapsed\(const value& start\);/);
  assert.match(header, /value time_format_duration\(const value& milliseconds\);/);
  assert.match(runtime, /double time_require_milliseconds\(const value& input, const std::string& message\)/);
  assert.match(runtime, /std::chrono::steady_clock::now\(\)\.time_since_epoch\(\)/);
  assert.match(runtime, /std::chrono::duration_cast<std::chrono::milliseconds>\(now\)\.count\(\)/);
  assert.match(runtime, /return time_require_milliseconds\(input, "Jayess time seconds expects a finite number"\) \* 1000\.0;/);
  assert.match(runtime, /return time_require_milliseconds\(input, "Jayess time minutes expects a finite number"\) \* 60000\.0;/);
  assert.match(runtime, /value time_elapsed\(const value& start\) \{/);
  assert.match(runtime, /value time_format_duration\(const value& milliseconds\) \{/);
  assert.match(runtime, /output << minutes << "m ";/);
});

test("runtime system-module helpers stay explicit and use a narrow native adapter layer", () => {
  const header = getRuntimeHeaderSource();
  const runtime = getRuntimeCppSource();

  assert.match(header, /value fs_exists_path\(const std::string& pathText\);/);
  assert.match(header, /value fs_exists_path_async\(const std::string& pathText\);/);
  assert.match(header, /value fs_read_text_file\(const std::string& pathText\);/);
  assert.match(header, /value fs_read_text_file_async\(const std::string& pathText\);/);
  assert.match(header, /value fs_write_text_file\(const std::string& pathText, const std::string& text\);/);
  assert.match(header, /value fs_write_text_file_async\(const std::string& pathText, const std::string& text\);/);
  assert.match(header, /value fs_create_directories\(const std::string& pathText\);/);
  assert.match(header, /value fs_create_directories_async\(const std::string& pathText\);/);
  assert.match(header, /value path_join_parts\(const std::vector<std::string>& parts\);/);
  assert.match(header, /value path_dirname\(const std::string& pathText\);/);
  assert.match(header, /value path_basename\(const std::string& pathText\);/);
  assert.match(header, /value path_extname\(const std::string& pathText\);/);
  assert.match(header, /value path_normalize\(const std::string& pathText\);/);
  assert.match(header, /value process_current_working_directory\(\);/);
  assert.match(header, /value process_get_env\(const std::string& key\);/);
  assert.match(header, /value process_has_env\(const std::string& key\);/);
  assert.match(header, /value process_set_exit_code\(int code\);/);
  assert.match(header, /\[\[noreturn\]\] void process_exit_with_code\(int code\);/);
  assert.match(runtime, /std::filesystem::path fs_require_path\(const std::string& pathText\)/);
  assert.match(runtime, /value fs_async_result\(std::function<value\(\)> operation\) \{/);
  assert.match(runtime, /const auto result = make_pending_async\(\);/);
  assert.match(runtime, /async_schedule\(\[result, operation = std::move\(operation\)\]\(\) mutable \{/);
  assert.match(runtime, /async_resolve\(result, operation\(\)\);/);
  assert.match(runtime, /async_reject\(result, exception_to_value\(error\)\);/);
  assert.match(runtime, /std::filesystem::path path_require_filesystem_path\(const std::string& pathText\)/);
  assert.match(runtime, /return std::filesystem::exists\(fs_require_path\(pathText\)\);/);
  assert.match(runtime, /std::ifstream stream\(fs_require_path\(pathText\), std::ios::binary\);/);
  assert.match(runtime, /std::ofstream stream\(fs_require_path\(pathText\), std::ios::binary\);/);
  assert.match(runtime, /return std::filesystem::create_directories\(fs_require_path\(pathText\)\);/);
  assert.match(runtime, /joined \/\= std::filesystem::path\(part\);/);
  assert.match(runtime, /return path_string_value\(joined\.lexically_normal\(\)\);/);
  assert.match(runtime, /return path_string_value\(path_require_filesystem_path\(pathText\)\.parent_path\(\)\);/);
  assert.match(runtime, /return path_string_value\(path_require_filesystem_path\(pathText\)\.filename\(\)\);/);
  assert.match(runtime, /return path_string_value\(path_require_filesystem_path\(pathText\)\.extension\(\)\);/);
  assert.match(runtime, /return path_string_value\(path_require_filesystem_path\(pathText\)\.lexically_normal\(\)\);/);
  assert.match(runtime, /return path_string_value\(std::filesystem::current_path\(\)\);/);
  assert.match(runtime, /const auto\* envValue = std::getenv\(key\.c_str\(\)\);/);
  assert.match(runtime, /return value\(std::monostate\{\}\);/);
  assert.match(runtime, /std::exit\(code\);/);
});
