import test from "node:test";
import assert from "node:assert/strict";
import { getRuntimeCppSource, getRuntimeHeaderSource } from "../src/cpp/runtime-source.js";

test("runtime iterator module helpers consume Jayess generator handles", () => {
  const header = getRuntimeHeaderSource();
  const runtime = getRuntimeCppSource();

  assert.match(header, /value iter_next\(const value& generator, const value& sent = value\(std::monostate\{\}\)\);/);
  assert.match(header, /value iter_to_array\(const value& generator\);/);
  assert.match(header, /value iter_take\(const value& generator, const value& count\);/);
  assert.match(header, /value iter_map\(const value& generator, const value& callback\);/);
  assert.match(header, /value iter_filter\(const value& generator, const value& callback\);/);
  assert.match(header, /value iter_for_each\(const value& generator, const value& callback\);/);
  assert.match(header, /value iter_reduce\(const value& generator, const value& callback, const value& initial\);/);
  assert.match(header, /value iter_some\(const value& generator, const value& callback\);/);
  assert.match(header, /value iter_every\(const value& generator, const value& callback\);/);
  assert.match(header, /value iter_find\(const value& generator, const value& callback\);/);
  assert.match(header, /value iter_chain\(const value& left, const value& right\);/);
  assert.match(header, /value iter_range\(const value& start, const value& end, const value& step\);/);
  assert.match(runtime, /const generator_ptr& require_iter_generator\(const value& input\)/);
  assert.match(runtime, /const callable_ptr& require_iter_callback\(const value& input\)/);
  assert.match(runtime, /std::size_t require_iter_count\(const value& input\)/);
  assert.match(runtime, /double require_iter_number\(const value& input, const std::string& message\)/);
  assert.match(runtime, /value iter_next\(const value& generator, const value& sent\)/);
  assert.match(runtime, /const auto current = generator_resume_with\(generator, sent\);/);
  assert.match(runtime, /value iter_to_array\(const value& generator\)/);
  assert.match(runtime, /value iter_map\(const value& generator, const value& callback\)/);
  assert.match(runtime, /value iter_filter\(const value& generator, const value& callback\)/);
  assert.match(runtime, /value iter_for_each\(const value& generator, const value& callback\)/);
  assert.match(runtime, /value iter_reduce\(const value& generator, const value& callback, const value& initial\)/);
  assert.match(runtime, /value iter_some\(const value& generator, const value& callback\)/);
  assert.match(runtime, /value iter_every\(const value& generator, const value& callback\)/);
  assert.match(runtime, /value iter_find\(const value& generator, const value& callback\)/);
  assert.match(runtime, /value iter_chain\(const value& left, const value& right\)/);
  assert.match(runtime, /value iter_range\(const value& start, const value& end, const value& step\)/);
  assert.match(runtime, /generator_set_resume\(chained, \[chained, left, right, phase = 0\]\(\) mutable \{/);
  assert.match(runtime, /generator_set_resume\(ranged, \[ranged, current = startNumber, endNumber, stepNumber\]\(\) mutable \{/);
});

test("runtime async helpers stay explicit and Jayess-owned", () => {
  const header = getRuntimeHeaderSource();
  const runtime = getRuntimeCppSource();

  assert.match(header, /enum class async_status/);
  assert.match(header, /struct async_state/);
  assert.match(header, /using async_ptr = std::shared_ptr<async_state>;/);
  assert.match(header, /using event_emitter_ptr = std::shared_ptr<event_emitter>;/);
  assert.match(header, /using stream_ptr = std::shared_ptr<stream_state>;/);
  assert.match(header, /value make_pending_async\(\);/);
  assert.match(header, /value make_resolved_async\(value resolved\);/);
  assert.match(header, /value make_rejected_async\(value rejected\);/);
  assert.match(header, /value async_all\(const value& handles\);/);
  assert.match(header, /value async_race\(const value& handles\);/);
  assert.match(header, /value async_all_settled\(const value& handles\);/);
  assert.match(header, /value async_any\(const value& handles\);/);
  assert.match(header, /value async_sleep\(const value& milliseconds\);/);
  assert.match(header, /value async_timeout\(const value& handle, const value& milliseconds\);/);
  assert.match(header, /value async_catch_error\(const value& handle, const value& callback\);/);
  assert.match(header, /value async_finally_do\(const value& handle, const value& callback\);/);
  assert.match(header, /value async_delay\(const value& input, const value& milliseconds\);/);
  assert.match(header, /value async_retry\(const value& callback, const value& count\);/);
  assert.match(header, /void async_schedule\(std::function<void\(\)> continuation\);/);
  assert.match(header, /void async_enqueue\(const value& input, std::function<void\(\)> continuation\);/);
  assert.match(header, /void run_async_scheduler\(\);/);
  assert.match(runtime, /std::deque<std::function<void\(\)>> queue;/);
  assert.match(runtime, /struct async_timer_record/);
  assert.match(runtime, /std::vector<async_timer_record>& async_scheduler_timers\(\)/);
  assert.match(runtime, /void async_schedule_timer\(int milliseconds, std::function<void\(\)> continuation\)/);
  assert.match(runtime, /void async_enqueue_due_timers\(\)/);
  assert.match(runtime, /value make_pending_async\(\) \{\s*return std::make_shared<async_state>\(\);/);
  assert.match(runtime, /state->status = async_status::resolved;/);
  assert.match(runtime, /state->status = async_status::rejected;/);
  assert.match(runtime, /bool is_async\(const value& input\) \{\s*return std::holds_alternative<async_ptr>\(input\);/);
  assert.match(runtime, /const array_ptr& require_async_handle_array\(const value& input\)/);
  assert.match(runtime, /void require_async_handle_items\(const array_ptr& array\)/);
  assert.match(runtime, /value async_all\(const value& handles\) \{/);
  assert.match(runtime, /if \(array->items\.empty\(\)\) \{\s*async_resolve\(result, make_array\(\{\}\)\);/);
  assert.match(runtime, /if \(!is_async\(handle\)\) \{\s*throw std::runtime_error\("Jayess async composition requires async handles"\);/);
  assert.match(runtime, /if \(async_is_rejected\(handle\)\) \{\s*\*settled = true;\s*async_reject\(result, async_result_value\(handle\)\);/);
  assert.match(runtime, /value async_race\(const value& handles\) \{/);
  assert.match(runtime, /async_reject\(result, value\(std::string\("Jayess async race requires at least one handle"\)\)\);/);
  assert.match(runtime, /value async_all_settled\(const value& handles\) \{/);
  assert.match(runtime, /\{"status", value\(std::string\("resolved"\)\)\}/);
  assert.match(runtime, /\{"reason", async_result_value\(handle\)\}/);
  assert.match(runtime, /value async_any\(const value& handles\) \{/);
  assert.match(runtime, /Jayess async any requires at least one handle/);
  assert.match(runtime, /async_reject\(result, make_array\(std::move\(\*rejections\)\)\);/);
  assert.match(runtime, /int require_async_milliseconds\(const value& input, const std::string& message\)/);
  assert.match(runtime, /Jayess async sleep expects a non-negative integer milliseconds value/);
  assert.match(runtime, /value async_sleep\(const value& milliseconds\) \{/);
  assert.match(runtime, /async_schedule_timer\(delay, \[result\]\(\) mutable \{/);
  assert.match(runtime, /value async_timeout\(const value& handle, const value& milliseconds\) \{/);
  assert.match(runtime, /async_schedule_timer\(delay, \[result, settled\]\(\) mutable \{/);
  assert.match(runtime, /Jayess async timeout expects a non-negative integer milliseconds value/);
  assert.match(runtime, /Jayess async operation timed out/);
  assert.match(runtime, /callable_ptr require_async_callback\(const value& input, const std::string& message\)/);
  assert.match(runtime, /void async_adopt_result\(const value& result, const value& produced\)/);
  assert.match(runtime, /value async_catch_error\(const value& handle, const value& callback\) \{/);
  assert.match(runtime, /value async_finally_do\(const value& handle, const value& callback\) \{/);
  assert.match(runtime, /value async_delay\(const value& input, const value& milliseconds\) \{/);
  assert.match(runtime, /value async_retry\(const value& callback, const value& countValue\) \{/);
  assert.match(runtime, /Jayess async retry exhausted/);
  assert.doesNotMatch(runtime, /std::this_thread::sleep_for\(std::chrono::milliseconds\(delay\)\);/);
  assert.match(runtime, /value await_sync\(const value& input\) \{/);
  assert.match(runtime, /if \(!is_async\(input\)\) \{\s*return input;/);
  assert.match(runtime, /if \(async_is_pending\(input\)\) \{\s*run_async_scheduler\(\);/);
  assert.match(runtime, /if \(async_is_rejected\(input\)\) \{\s*throw_value\(async_result_value\(input\)\);/);
  assert.match(runtime, /void async_resolve\(const value& input, value resolved\)/);
  assert.match(runtime, /void async_reject\(const value& input, value rejected\)/);
  assert.match(runtime, /void async_schedule\(std::function<void\(\)> continuation\) \{\s*async_scheduler_queue\(\)\.push_back\(std::move\(continuation\)\);/);
  assert.match(runtime, /if \(state->status == async_status::pending\) \{\s*state->continuations.push_back/);
  assert.match(runtime, /if \(queue\.empty\(\)\) \{\s*async_enqueue_due_timers\(\);/);
});

test("runtime generator helpers stay explicit and Jayess-owned", () => {
  const header = getRuntimeHeaderSource();
  const runtime = getRuntimeCppSource();

  assert.match(header, /enum class generator_status/);
  assert.match(header, /struct generator_state/);
  assert.match(header, /using generator_ptr = std::shared_ptr<generator_state>;/);
  assert.match(header, /value make_generator_handle\(\);/);
  assert.match(header, /bool is_generator\(const value& input\);/);
  assert.match(header, /std::size_t generator_next_state\(const value& input\);/);
  assert.match(header, /value generator_current_value\(const value& input\);/);
  assert.match(header, /void generator_set_resume\(const value& input, std::function<void\(\)> resume\);/);
  assert.match(header, /void generator_yield\(const value& input, std::size_t nextState, value yielded\);/);
  assert.match(header, /void generator_complete\(const value& input, value completed\);/);
  assert.match(header, /void generator_fail\(const value& input, value failure\);/);
  assert.match(header, /value generator_take_sent\(const value& input\);/);
  assert.match(header, /value generator_resume\(const value& input\);/);
  assert.match(header, /value generator_resume_with\(const value& input, value sent\);/);
  assert.match(runtime, /value make_generator_handle\(\) \{\s*return std::make_shared<generator_state>\(\);/);
  assert.match(runtime, /bool is_generator\(const value& input\) \{\s*return std::holds_alternative<generator_ptr>\(input\);/);
  assert.match(header, /value sent = std::monostate\{\};/);
  assert.match(runtime, /state->status == generator_status::suspended_start \|\| state->status == generator_status::suspended_yield/);
  assert.match(runtime, /std::size_t generator_next_state\(const value& input\) \{\s*return require_generator_state\(input\)->next_state;/);
  assert.match(runtime, /value generator_current_value\(const value& input\) \{\s*return require_generator_state\(input\)->current;/);
  assert.match(runtime, /state->status = generator_status::suspended_yield;/);
  assert.match(runtime, /state->next_state = nextState;/);
  assert.match(runtime, /state->status = generator_status::completed;/);
  assert.match(runtime, /state->status = generator_status::failed;/);
  assert.match(runtime, /value generator_take_sent\(const value& input\) \{/);
  assert.match(runtime, /state->sent = std::move\(sent\);/);
  assert.match(runtime, /if \(!state->resume\) \{\s*throw std::runtime_error\("Generator has no resume function"\);/);
  assert.match(runtime, /state->resume\(\);/);
  assert.match(runtime, /if \(state->status == generator_status::failed\) \{\s*throw_value\(state->current\);/);
  assert.match(runtime, /return state->current;/);
});

test("runtime class-chain helpers stay explicit and Jayess-owned", () => {
  const header = getRuntimeHeaderSource();
  const runtime = getRuntimeCppSource();

  assert.match(header, /value set_base_class\(const value& classValue, const value& baseClass\);/);
  assert.match(header, /value get_base_class\(const value& classValue\);/);
  assert.match(header, /value set_instance_class\(const value& instance, const value& classValue\);/);
  assert.match(header, /value get_instance_class\(const value& instance\);/);
  assert.match(header, /value find_class_method\(const value& classValue, const std::string& key\);/);
  assert.match(runtime, /constexpr const char\* kJayessBaseClassKey = "__jayess_base_class";/);
  assert.match(runtime, /constexpr const char\* kJayessInstanceClassKey = "__jayess_class";/);
  assert.match(runtime, /callable_ptr require_class_value\(const value& input\)/);
  assert.match(runtime, /object_ptr require_instance_object\(const value& input\)/);
  assert.match(runtime, /value set_base_class\(const value& classValue, const value& baseClass\) \{/);
  assert.match(runtime, /callable->fields\.insert_or_assign\(kJayessBaseClassKey, baseClass\);/);
  assert.match(runtime, /value get_base_class\(const value& classValue\) \{/);
  assert.match(runtime, /return value\(std::monostate\{\}\);/);
  assert.match(runtime, /value set_instance_class\(const value& instance, const value& classValue\) \{/);
  assert.match(runtime, /object->fields\.insert_or_assign\(kJayessInstanceClassKey, classValue\);/);
  assert.match(runtime, /value find_class_method\(const value& classValue, const std::string& key\) \{/);
  assert.match(runtime, /while \(!std::holds_alternative<std::monostate>\(current\)\) \{/);
  assert.match(runtime, /current = get_base_class\(current\);/);
  assert.match(runtime, /throw std::runtime_error\("Missing class method"\);/);
  assert.match(header, /value find_static_class_member\(const value& classValue, const std::string& key\);/);
  assert.match(runtime, /value find_static_class_member\(const value& classValue, const std::string& key\) \{/);
  assert.match(runtime, /return find_static_class_member\(input, key\);/);
});

test("runtime private-field helpers stay non-public and class-owned", () => {
  const header = getRuntimeHeaderSource();
  const runtime = getRuntimeCppSource();

  assert.match(header, /std::unordered_map<std::string, value> private_fields;/);
  assert.match(header, /value get_private_field\(const value& instance, const value& classValue, const std::string& key\);/);
  assert.match(header, /value set_private_field\(const value& instance, const value& classValue, const std::string& key, const value& assigned\);/);
  assert.match(header, /value get_private_static_field\(const value& classValue, const std::string& key\);/);
  assert.match(header, /value set_private_static_field\(const value& classValue, const std::string& key, const value& assigned\);/);
  assert.match(runtime, /constexpr const char\* kJayessPrivateFieldPrefix = "__jayess_private_";/);
  assert.match(runtime, /constexpr const char\* kJayessPrivateStaticFieldPrefix = "__jayess_private_static_";/);
  assert.match(runtime, /std::string private_field_storage_key\(const value& classValue, const std::string& key\)/);
  assert.match(runtime, /stream << kJayessPrivateFieldPrefix << require_private_class_value\(classValue\)\.get\(\) << "_" << key;/);
  assert.match(runtime, /value get_private_static_field\(const value& classValue, const std::string& key\)/);
  assert.match(runtime, /callable->fields\.insert_or_assign\(storageKey, assigned\);/);
  assert.match(runtime, /const auto iterator = object->private_fields\.find\(storageKey\);/);
  assert.match(runtime, /object->private_fields\.insert_or_assign\(storageKey, assigned\);/);
  assert.doesNotMatch(runtime, /get_property\(const value& input, const std::string& key\) \{[\s\S]*private_fields/);
});
